version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            01:15:67:1b:74:2a:49:98:aa:ab:93:3f:3e:81:7a:1b
      - run:
          name: Build image
          command: |
            ssh gel0@35.228.159.44 "cd ~/anaconda_pkgs_to_remove_addon; git pull"
            ssh gel0@35.228.159.44 "cd ~/anaconda_pkgs_to_remove_addon; make"
workflows:
  version: 2
  workflow:
    jobs:
      - build