version: 2
jobs:
  buid:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkput
      - add_ssh_keys:
          fingerprints:
            82:f8:79:47:52:1e:6e:61:c7:04:a2:79:6c:c1:21:0f
      - run:
          name: Build image
          command: |
            ssh gel0@35.228.159.44 "cd ~/anaconda_pkgs_to_remove_addon; git pull"
            ssh gel0@35.228.159.44 "cd ~/anaconda_pkgs_to_remove_addon; make"
            ssh gel0@35.228.159.44 "cd ~/anaconda_pkgs_to_remove_addon; cp -u updates.img ~/"
workflows:
  version: 2
  workflow:
    jobs:
      - buid